spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jrtp25
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    view:
      prefix: '/templates/'
      suffix: '.html'

  # SMTP PROPS
  mail:
    host: smtp.gmail.com
    port: 587
    username: udaykiran87126@gmail.com
    password: 'kwye pgmg iaba bhgl'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
